# Frontman Server
# Copyright (C) 2025 Frontman AI
#
# Licensed under the AGPL-3.0 — see LICENSE for details.
# Additional terms apply — see AI-SUPPLEMENTARY-TERMS.md

defmodule FrontmanServerWeb.Endpoint do
  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :frontman_server

  alias FrontmanServerWeb.Plugs.SandboxPreviewProxy
  alias Plug.Session

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_frontman_server_key",
    signing_salt: "4+DQeuxI",
    same_site: "None",
    secure: true
  ]

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  socket("/socket", FrontmanServerWeb.UserSocket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: false
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :frontman_server,
    gzip: not code_reloading?,
    only: FrontmanServerWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :frontman_server)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])
  plug(:session_and_preview_proxy)

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Sentry.PlugContext)
  plug(FrontmanServerWeb.Plugs.CORS, path_prefix: "/api")
  plug(FrontmanServerWeb.Router)

  defp session_and_preview_proxy(conn, _opts) do
    conn
    |> Session.call(Session.init(session_options_with_domain()))
    |> SandboxPreviewProxy.call(SandboxPreviewProxy.init([]))
  end

  defp session_options_with_domain do
    case Application.get_env(:frontman_server, :auth_cookie_domain) do
      domain when is_binary(domain) and byte_size(domain) > 0 ->
        Keyword.put(@session_options, :domain, domain)

      _ ->
        @session_options
    end
  end
end
