[[language]]
name = "rescript"
workspace-lsp-roots = [
  "libs/bindings",
  "libs/client",
  "libs/experimental-rescript-webapi",
  "libs/frontman-astro",
  "libs/frontman-astro-browser",
  "libs/frontman-client",
  "libs/frontman-core",
  "libs/frontman-nextjs",
  "libs/frontman-protocol",
  "libs/frontman-vite",
  "libs/logs",
  "libs/react-statestore",
]
