import { defineConfig } from 'tsup';
import { readFileSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

export default defineConfig([
  {
    entry: { 'index': './src/FrontmanNextjs.res.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: true,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: [
      '@frontman-ai/frontman-core',
      '@frontman-ai/frontman-protocol',
      '@frontman/bindings',
      '@rescript/runtime',
      'sury',
      'dom-element-to-component-source',
    ],
    external: [
      '@sentry/nextjs',
      '@opentelemetry/api',
      '@opentelemetry/sdk-logs',
      '@opentelemetry/sdk-trace-base',
      '@opentelemetry/sdk-node',
      'next',
      'next/server',
      'react',
      'react-dom',
      'lighthouse',
      'chrome-launcher',
      'fs',
      'path',
      'os',
      'child_process',
      'crypto',
      'util',
      'stream',
      'events',
      'buffer',
      'url',
      'http',
      'https',
      'net',
      'tls',
      'zlib',
      'readline',
      'tty',
      'assert',
      'process',
    ],
    platform: 'node',
    target: 'node18',
    treeshake: true,
  },
  {
    entry: { 'instrumentation': './src/FrontmanNextjs__Instrumentation.res.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: false,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: [
      '@frontman-ai/frontman-core',
      '@frontman-ai/frontman-protocol',
      '@frontman/bindings',
      '@rescript/runtime',
      'sury',
      'dom-element-to-component-source',
    ],
    external: [
      '@sentry/nextjs',
      '@opentelemetry/api',
      '@opentelemetry/sdk-logs',
      '@opentelemetry/sdk-trace-base',
      '@opentelemetry/sdk-node',
      'next',
      'next/server',
      'react',
      'react-dom',
      'lighthouse',
      'chrome-launcher',
      'fs',
      'path',
      'os',
      'child_process',
      'crypto',
      'util',
      'stream',
      'events',
      'buffer',
      'url',
      'http',
      'https',
      'net',
      'tls',
      'zlib',
      'readline',
      'tty',
      'assert',
      'process',
    ],
    platform: 'node',
    target: 'node18',
    treeshake: true,
  },
  {
    entry: { 'cli': './src/cli/cli.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: false,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: [
      '@frontman-ai/frontman-core',
      '@frontman-ai/frontman-protocol',
      '@frontman/bindings',
      '@rescript/runtime',
      'sury',
      'dom-element-to-component-source',
    ],
    external: [
      '@sentry/nextjs',
      '@opentelemetry/api',
      '@opentelemetry/sdk-logs',
      '@opentelemetry/sdk-trace-base',
      '@opentelemetry/sdk-node',
      'next',
      'next/server',
      'react',
      'react-dom',
      'lighthouse',
      'chrome-launcher',
      'fs',
      'path',
      'os',
      'child_process',
      'crypto',
      'util',
      'stream',
      'events',
      'buffer',
      'url',
      'http',
      'https',
      'net',
      'tls',
      'zlib',
      'readline',
      'tty',
      'assert',
      'process',
    ],
    platform: 'node',
    target: 'node18',
    treeshake: true,
  },
]);
