#!/bin/bash
# caddy-regen.sh — Regenerate Caddyfile from running worktree pods.
#
# Scans all running worktree-* pods, reads their published port mappings,
# generates reverse proxy routes for each one, writes the Caddyfile that
# Caddy's bind mount points to, and reloads Caddy.
#
# Networking: Caddy runs with --network=host and routes to 127.0.0.1:<port>.
# Each pod publishes deterministic ports derived from its hash.
#
# Usage: ./infra/local/caddy-regen.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADDY_CONTAINER="frontman-caddy"

# Resolve the Caddyfile path from the container's bind mount so we always
# write to the file Caddy is actually reading, regardless of which worktree
# invokes this script. Falls back to $SCRIPT_DIR/Caddyfile if the container
# isn't running yet (e.g. first-time infra-up).
CADDYFILE="$SCRIPT_DIR/Caddyfile"
if podman container inspect "$CADDY_CONTAINER" &>/dev/null; then
    MOUNT_SRC=$(podman inspect "$CADDY_CONTAINER" \
        --format '{{range .Mounts}}{{if eq .Destination "/etc/caddy/Caddyfile"}}{{.Source}}{{end}}{{end}}' 2>/dev/null || true)
    if [ -n "$MOUNT_SRC" ]; then
        CADDYFILE="$MOUNT_SRC"
    fi
fi

# Collect running worktree pods
PODS=$(podman pod ls --format '{{.Name}}' --filter status=running 2>/dev/null | grep '^worktree-' || true)

# Start generating Caddyfile
cat > "$CADDYFILE" << 'HEADER'
# Auto-generated by caddy-regen.sh — DO NOT EDIT MANUALLY
# Regenerate with: ./infra/local/caddy-regen.sh

HEADER

if [ -z "$PODS" ]; then
    # No pods running — write a minimal Caddyfile so Caddy doesn't error
    cat >> "$CADDYFILE" << 'EOF'
# No worktree pods currently running.
# Create one with: make wt-new BRANCH=feature/my-feature
:9999 {
    respond "No worktree pods running" 503
}
EOF
else
    for POD in $PODS; do
        # Extract hash from pod name (worktree-HASH)
        HASH="${POD#worktree-}"

        # Derive ports from hash (must match bin/wt-pod-create)
        # Base port range uses 5-port strides to avoid overlap:
        # (0xHASH % 1000) * 5 + 10000
        BASE_PORT=$(( (16#${HASH} % 1000) * 5 + 10000 ))
        PORT_PHOENIX=$((BASE_PORT))
        PORT_VITE=$((BASE_PORT + 1))
        PORT_NEXTJS=$((BASE_PORT + 2))
        PORT_STORYBOOK=$((BASE_PORT + 3))
        PORT_MARKETING=$((BASE_PORT + 4))

        # Generate route blocks for this worktree
        cat >> "$CADDYFILE" << EOF
# Worktree: $POD (ports ${PORT_PHOENIX}–${PORT_MARKETING})
${HASH}.api.frontman.local {
    tls internal
    reverse_proxy https://127.0.0.1:${PORT_PHOENIX} {
        transport http {
            tls_insecure_skip_verify
        }
    }
}

${HASH}.vite.frontman.local {
    tls internal
    reverse_proxy 127.0.0.1:${PORT_VITE}
}

${HASH}.nextjs.frontman.local {
    tls internal
    reverse_proxy 127.0.0.1:${PORT_NEXTJS}
}

${HASH}.storybook.frontman.local {
    tls internal
    reverse_proxy 127.0.0.1:${PORT_STORYBOOK}
}

${HASH}.marketing.frontman.local {
    tls internal
    reverse_proxy 127.0.0.1:${PORT_MARKETING}
}

EOF
    done
fi

echo "Generated $CADDYFILE"

# Reload Caddy if running
if podman container inspect "$CADDY_CONTAINER" &>/dev/null; then
    podman exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile 2>/dev/null && \
        echo "Caddy reloaded" || \
        echo "Warning: Caddy reload failed (container may not be running)"
else
    echo "Note: Caddy container ($CADDY_CONTAINER) not running — skipping reload"
fi
