#!/bin/bash
# caddy-regen.sh — Regenerate Caddyfile from running worktree pods.
#
# Scans all running worktree-* pods, generates reverse proxy routes
# for each one, writes infra/local/Caddyfile, and reloads Caddy.
#
# Usage: ./infra/local/caddy-regen.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADDYFILE="$SCRIPT_DIR/Caddyfile"
CADDY_CONTAINER="frontman-caddy"

# Collect running worktree pods
PODS=$(podman pod ls --format '{{.Name}}' --filter status=running 2>/dev/null | grep '^worktree-' || true)

# Start generating Caddyfile
cat > "$CADDYFILE" << 'HEADER'
# Auto-generated by caddy-regen.sh — DO NOT EDIT MANUALLY
# Regenerate with: ./infra/local/caddy-regen.sh

HEADER

if [ -z "$PODS" ]; then
    # No pods running — write a minimal Caddyfile so Caddy doesn't error
    cat >> "$CADDYFILE" << 'EOF'
# No worktree pods currently running.
# Create one with: make worktree-pod-create BRANCH=feature/my-feature
:80 {
    respond "No worktree pods running" 503
}
EOF
else
    for POD in $PODS; do
        # Extract hash from pod name (worktree-HASH)
        HASH="${POD#worktree-}"

        # Generate route blocks for this worktree
        cat >> "$CADDYFILE" << EOF
# Worktree: $POD
${HASH}.api.frontman.local {
    tls internal
    reverse_proxy https://${POD}:4000 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}

${HASH}.vite.frontman.local {
    tls internal
    reverse_proxy ${POD}:5173
}

${HASH}.nextjs.frontman.local {
    tls internal
    reverse_proxy ${POD}:3000
}

${HASH}.storybook.frontman.local {
    tls internal
    reverse_proxy ${POD}:6006
}

${HASH}.dogfood.frontman.local {
    tls internal
    reverse_proxy ${POD}:6123
}

${HASH}.marketing.frontman.local {
    tls internal
    reverse_proxy ${POD}:4321
}

EOF
    done
fi

echo "Generated $CADDYFILE"

# Reload Caddy if running
if podman container inspect "$CADDY_CONTAINER" &>/dev/null; then
    podman exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile 2>/dev/null && \
        echo "Caddy reloaded" || \
        echo "Warning: Caddy reload failed (container may not be running)"
else
    echo "Note: Caddy container ($CADDY_CONTAINER) not running — skipping reload"
fi
