/**
 * DSL Converter
 * Converts Figma node skeletons to a compact DSL format optimized for AI consumption
 * 
 * Core principle: If expanding a node wouldn't change the implementation approach, don't expand it.
 */

import type { CompactNodeSkeleton, NodeSkeleton } from "./types.js";

// ============================================================================
// Types
// ============================================================================

export interface DSLConversionOptions {
  /** Include source file reference at the top (e.g., @source: filename) */
  sourceFile?: string;
  /** Minimum indentation level (default: 0) */
  baseIndent?: number;
  /** Characters per indent level (default: 2) */
  indentSize?: number;
}

// ============================================================================
// Volume Calculation
// ============================================================================

/**
 * Volume scale based on total token count
 */
export function calculateVolume(totalTokens: number): number {
  if (totalTokens < 100) return 1;
  if (totalTokens < 500) return 2;
  if (totalTokens < 1000) return 3;
  if (totalTokens < 2000) return 4;
  if (totalTokens < 5000) return 5;
  if (totalTokens < 10000) return 6;
  if (totalTokens < 25000) return 7;
  if (totalTokens < 100000) return 8;
  if (totalTokens < 500000) return 9;
  return 10;
}

// ============================================================================
// Name Classification
// ============================================================================

// Generic names that don't add semantic value
const GENERIC_NAMES = new Set([
  "container",
  "group",
  "frame",
  "div",
  "wrapper",
  "box",
  "stack",
  "row",
  "col",
  "view",
  "layer",
]);

// Patterns to detect auto-generated Figma names
const AUTO_GENERATED_PATTERNS = [
  /^Frame\s*\d+$/i,
  /^Group\s*\d+$/i,
  /^Rectangle\s*\d*$/i,
  /^Ellipse\s*\d*$/i,
  /^Vector\s*\d*$/i,
  /^Line\s*\d*$/i,
  /^Polygon\s*\d*$/i,
];

// Icon library patterns
const ICON_LIBRARY_PATTERNS = [
  /^vuesax/i,
  /^solar[-_]/i,
  /^eva:/i,
  /^lucide[-_]/i,
  /^heroicon/i,
  /^feather[-_]/i,
  /^phosphor[-_]/i,
  /^tabler[-_]/i,
  /^radix[-_]/i,
  /^icon[-_]/i,
  /^ic[-_]/i,
  /^icons?\//i,
];

// Icon type mappings (extract semantic type from icon name)
// Order matters: more specific patterns should come first
const ICON_TYPE_PATTERNS: Array<{ pattern: RegExp; type: string }> = [
  { pattern: /check|tick|done|success/i, type: "check" },
  { pattern: /close|x[-_]|cancel|dismiss/i, type: "close" },
  { pattern: /star|rating|favorite/i, type: "star" },
  { pattern: /info|circle[-_]i|about/i, type: "info" },
  { pattern: /add|plus|create|new/i, type: "add" },
  { pattern: /arrow|chevron|caret/i, type: "arrow" },
  { pattern: /search|find|magnif/i, type: "search" },
  { pattern: /menu|hamburger|bars/i, type: "menu" },
  { pattern: /user|person|profile|avatar/i, type: "user" },
  { pattern: /settings|gear|cog/i, type: "settings" },
  { pattern: /edit|pencil|pen/i, type: "edit" },
  { pattern: /delete|trash|remove/i, type: "delete" },
  { pattern: /home|house/i, type: "home" },
  { pattern: /mail|email|envelope/i, type: "mail" },
  { pattern: /phone|call|mobile/i, type: "phone" },
  { pattern: /calendar|date|schedule/i, type: "calendar" },
  { pattern: /clock|time|timer/i, type: "clock" },
  { pattern: /lock|secure|password/i, type: "lock" },
  { pattern: /eye|view|visible|show/i, type: "eye" },
  { pattern: /heart|like|love/i, type: "heart" },
  { pattern: /share|social/i, type: "share" },
  { pattern: /download|export/i, type: "download" },
  { pattern: /upload|import/i, type: "upload" },
  { pattern: /copy|duplicate|clone/i, type: "copy" },
  { pattern: /link|chain|url/i, type: "link" },
  { pattern: /play|video|media/i, type: "play" },
  { pattern: /pause|stop/i, type: "pause" },
];

/**
 * Check if a name is auto-generated by Figma
 */
export function isAutoGeneratedName(name: string): boolean {
  return AUTO_GENERATED_PATTERNS.some((p) => p.test(name));
}

/**
 * Check if a name is generic (doesn't add semantic value)
 */
export function isGenericName(name: string): boolean {
  const normalized = name.toLowerCase().replace(/[-_\s]+/g, "");
  return GENERIC_NAMES.has(normalized) || isAutoGeneratedName(name);
}

/**
 * Check if a name matches icon library patterns
 */
export function isIconName(name: string): boolean {
  return ICON_LIBRARY_PATTERNS.some((p) => p.test(name));
}

/**
 * Extract icon type from a name
 */
export function extractIconType(name: string): string {
  // Try to match known icon types
  for (const { pattern, type } of ICON_TYPE_PATTERNS) {
    if (pattern.test(name)) {
      return type;
    }
  }

  // Fallback: extract last meaningful segment
  const segments = name.split(/[-_/]/);
  const lastSegment = segments[segments.length - 1]
    .toLowerCase()
    .replace(/[^a-z]/g, "");
  return lastSegment || "icon";
}

// ============================================================================
// Structural Comparison (Rule 4)
// ============================================================================

/**
 * Create a structural signature for a node (ignoring IDs and specific values)
 */
export function getStructuralSignature(node: CompactNodeSkeleton): string {
  const name = normalizeName(node.n);
  if (!node.c?.length) return name;

  const childSigs = node.c.map(getStructuralSignature).sort();
  return `${name}[${childSigs.join(",")}]`;
}

// ============================================================================
// Name Processing
// ============================================================================

/**
 * Normalize a name to lowercase with hyphens
 */
function normalizeName(name: string): string {
  // First check if it's auto-generated
  if (isAutoGeneratedName(name)) {
    return "container";
  }

  return name
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "") || "element";
}

/**
 * Check if a name looks like a price value
 */
export function isPriceValue(name: string): boolean {
  return (
    /^\$?\d+(\.\d{2})?$/.test(name) || /^\/\s*(month|year|seat)/i.test(name)
  );
}

/**
 * Check if a name is a plain number (list item index)
 */
export function isListIndex(name: string): boolean {
  return /^\d+$/.test(name);
}

// ============================================================================
// Legacy exports (for backward compatibility with tests)
// ============================================================================

export function extractIconId(name: string): string {
  return extractIconType(name);
}

export function inferSemanticName(
  name: string,
  _children?: CompactNodeSkeleton[]
): { name: string; isSection: boolean; isIcon: boolean; iconId?: string } {
  if (isIconName(name)) {
    return {
      name: "icon",
      isSection: false,
      isIcon: true,
      iconId: extractIconType(name),
    };
  }

  const normalized = normalizeName(name);
  const isSection =
    /^(section|for|pricing|individual|teams?|enterprise|header|footer)/i.test(
      name
    );

  return { name: normalized, isSection, isIcon: false };
}

export function detectListPattern(
  children: CompactNodeSkeleton[],
  _maxCollapseVolume: number = 3
): { isList: boolean; count: number; label?: string } {
  if (children.length < 2) {
    return { isList: false, count: 0 };
  }

  if (allChildrenSameName(children)) {
    const label = normalizeName(children[0].n);
    return { isList: true, count: children.length, label };
  }

  return { isList: false, count: 0 };
}

// ============================================================================
// DSL Generation
// ============================================================================

interface OutputContext {
  indentSize: number;
  lines: string[];
}

/**
 * Add a line to output with proper indentation
 */
function addLine(ctx: OutputContext, indent: number, content: string): void {
  ctx.lines.push(" ".repeat(indent * ctx.indentSize) + content);
}

/**
 * Process a node and its children, applying collapse rules
 */
function processNode(
  node: CompactNodeSkeleton,
  indent: number,
  ctx: OutputContext
): void {
  const volume = calculateVolume(node.t);
  const name = normalizeName(node.n);

  // Always expand fully; no collapsing or skipping
  if (!node.c || node.c.length === 0) {
    if (isPriceValue(node.n)) {
      addLine(ctx, indent, `price #${node.i}: "${node.n}"`);
    } else {
      addLine(ctx, indent, `${name} #${node.i}`);
    }
    return;
  }

  addLine(ctx, indent, `${name}(v:${volume}) #${node.i}:`);
  for (const child of node.c) {
    processNode(child, indent + 1, ctx);
  }
}

/**
 * Convert a CompactNodeSkeleton tree to DSL string
 */
export function skeletonToDSL(
  skeleton: CompactNodeSkeleton,
  options: DSLConversionOptions = {}
): string {
  const ctx: OutputContext = {
    indentSize: options.indentSize ?? 2,
    lines: [],
  };

  // Add source file reference if provided
  if (options.sourceFile) {
    ctx.lines.push(`@source: ${options.sourceFile}`);
  }

  // Process the tree starting from root
  const baseIndent = options.baseIndent ?? 0;
  processNode(skeleton, baseIndent, ctx);

  return ctx.lines.join("\n");
}

/**
 * Convert a NodeSkeleton (expanded format) to DSL string
 */
export function expandedSkeletonToDSL(
  skeleton: NodeSkeleton,
  options: DSLConversionOptions = {}
): string {
  const compact = compactSkeleton(skeleton);
  return skeletonToDSL(compact, options);
}

/**
 * Convert NodeSkeleton to CompactNodeSkeleton
 */
function compactSkeleton(skeleton: NodeSkeleton): CompactNodeSkeleton {
  return {
    i: skeleton.id,
    n: skeleton.name,
    s: skeleton.selfTokenCount,
    t: skeleton.totalTokenCount,
    c: skeleton.children?.map(compactSkeleton),
  };
}

/**
 * Convert multiple skeletons to DSL, separated by blank lines
 */
export function skeletonsToDSL(
  skeletons: CompactNodeSkeleton[],
  options: DSLConversionOptions = {}
): string {
  return skeletons.map((s) => skeletonToDSL(s, options)).join("\n\n");
}
