import { describe, it, expect } from "vitest";
import {
  calculateVolume,
  isAutoGeneratedName,
  isIconName,
  extractIconType,
  isGenericName,
  getStructuralSignature,
  isPriceValue,
  isListIndex,
  skeletonToDSL,
  expandedSkeletonToDSL,
  skeletonsToDSL,
} from "../src/dsl.js";
import type { CompactNodeSkeleton, NodeSkeleton } from "../src/types.js";

describe("calculateVolume", () => {
  it("should return v:1 for tiny nodes (< 100 tokens)", () => {
    expect(calculateVolume(0)).toBe(1);
    expect(calculateVolume(50)).toBe(1);
    expect(calculateVolume(99)).toBe(1);
  });

  it("should return v:2 for small nodes (100-499 tokens)", () => {
    expect(calculateVolume(100)).toBe(2);
    expect(calculateVolume(499)).toBe(2);
  });

  it("should return v:3 for medium nodes (500-999 tokens)", () => {
    expect(calculateVolume(500)).toBe(3);
    expect(calculateVolume(999)).toBe(3);
  });

  it("should return v:4 for moderate nodes (1K-2K tokens)", () => {
    expect(calculateVolume(1000)).toBe(4);
    expect(calculateVolume(1999)).toBe(4);
  });

  it("should return v:5 for standard nodes (2K-5K tokens)", () => {
    expect(calculateVolume(2000)).toBe(5);
    expect(calculateVolume(4999)).toBe(5);
  });

  it("should return v:6 for large nodes (5K-10K tokens)", () => {
    expect(calculateVolume(5000)).toBe(6);
    expect(calculateVolume(9999)).toBe(6);
  });

  it("should return v:7 for heavy nodes (10K-25K tokens)", () => {
    expect(calculateVolume(10000)).toBe(7);
    expect(calculateVolume(24999)).toBe(7);
  });

  it("should return v:8 for complex nodes (25K-100K tokens)", () => {
    expect(calculateVolume(25000)).toBe(8);
    expect(calculateVolume(99999)).toBe(8);
  });

  it("should return v:9 for massive nodes (100K-500K tokens)", () => {
    expect(calculateVolume(100000)).toBe(9);
    expect(calculateVolume(499999)).toBe(9);
  });

  it("should return v:10 for enormous nodes (>= 500K tokens)", () => {
    expect(calculateVolume(500000)).toBe(10);
    expect(calculateVolume(1000000)).toBe(10);
  });
});

describe("isAutoGeneratedName", () => {
  it("should detect Frame auto-names", () => {
    expect(isAutoGeneratedName("Frame 123")).toBe(true);
    expect(isAutoGeneratedName("Frame 2087327528")).toBe(true);
    expect(isAutoGeneratedName("frame 1")).toBe(true);
  });

  it("should detect Group auto-names", () => {
    expect(isAutoGeneratedName("Group 1")).toBe(true);
    expect(isAutoGeneratedName("group 123")).toBe(true);
  });

  it("should detect shape auto-names", () => {
    expect(isAutoGeneratedName("Rectangle")).toBe(true);
    expect(isAutoGeneratedName("Rectangle 1")).toBe(true);
    expect(isAutoGeneratedName("Ellipse")).toBe(true);
    expect(isAutoGeneratedName("Vector 3")).toBe(true);
    expect(isAutoGeneratedName("Line 1")).toBe(true);
  });

  it("should not match meaningful names", () => {
    expect(isAutoGeneratedName("header")).toBe(false);
    expect(isAutoGeneratedName("sidebar")).toBe(false);
    expect(isAutoGeneratedName("Frame Header")).toBe(false);
    expect(isAutoGeneratedName("My Frame")).toBe(false);
  });
});

describe("isIconName", () => {
  it("should detect icon library patterns", () => {
    expect(isIconName("vuesax-linear-check")).toBe(true);
    expect(isIconName("solar-check-circle")).toBe(true);
    expect(isIconName("eva:checkmark")).toBe(true);
    expect(isIconName("lucide-check")).toBe(true);
    expect(isIconName("heroicon-check")).toBe(true);
  });

  it("should detect icon paths and prefixes", () => {
    expect(isIconName("icons/ui/check")).toBe(true);
    expect(isIconName("icon-check")).toBe(true);
    expect(isIconName("ic-check")).toBe(true);
    expect(isIconName("ic_arrow")).toBe(true);
  });

  it("should not match non-icon names", () => {
    expect(isIconName("button")).toBe(false);
    expect(isIconName("iconic")).toBe(false);
    expect(isIconName("content")).toBe(false);
  });
});

describe("extractIconType", () => {
  it("should extract known icon types", () => {
    expect(extractIconType("vuesax-linear-check")).toBe("check");
    expect(extractIconType("solar-close-circle")).toBe("close");
    expect(extractIconType("ic-star-filled")).toBe("star");
    expect(extractIconType("icon-info")).toBe("info");
    expect(extractIconType("heroicon-plus")).toBe("add");
    expect(extractIconType("chevron-right")).toBe("arrow");
  });

  it("should fallback to last segment for unknown types", () => {
    expect(extractIconType("icons/custom/sparkle")).toBe("sparkle");
    expect(extractIconType("ic-notification")).toBe("notification");
  });
});

describe("isGenericName", () => {
  it("should identify generic container names", () => {
    expect(isGenericName("container")).toBe(true);
    expect(isGenericName("group")).toBe(true);
    expect(isGenericName("frame")).toBe(true);
    expect(isGenericName("wrapper")).toBe(true);
    expect(isGenericName("div")).toBe(true);
  });

  it("should identify auto-generated names as generic", () => {
    expect(isGenericName("Frame 123")).toBe(true);
    expect(isGenericName("Group 1")).toBe(true);
  });

  it("should not flag semantic names as generic", () => {
    expect(isGenericName("header")).toBe(false);
    expect(isGenericName("product-card")).toBe(false);
    expect(isGenericName("stars")).toBe(false);
  });
});

describe("getStructuralSignature", () => {
  it("should create signature for leaf nodes", () => {
    const node: CompactNodeSkeleton = { i: "0:1", n: "title", s: 10, t: 10 };
    expect(getStructuralSignature(node)).toBe("title");
  });

  it("should create signature for nodes with children", () => {
    const node: CompactNodeSkeleton = {
      i: "0:1",
      n: "card",
      s: 50,
      t: 100,
      c: [
        { i: "0:2", n: "title", s: 25, t: 25 },
        { i: "0:3", n: "subtitle", s: 25, t: 25 },
      ],
    };
    expect(getStructuralSignature(node)).toBe("card[subtitle,title]");
  });

  it("should produce identical signatures for structurally identical nodes", () => {
    const node1: CompactNodeSkeleton = {
      i: "0:1",
      n: "row",
      s: 50,
      t: 100,
      c: [
        { i: "0:2", n: "cell", s: 25, t: 25 },
        { i: "0:3", n: "cell", s: 25, t: 25 },
      ],
    };
    const node2: CompactNodeSkeleton = {
      i: "0:10",
      n: "row",
      s: 50,
      t: 100,
      c: [
        { i: "0:11", n: "cell", s: 25, t: 25 },
        { i: "0:12", n: "cell", s: 25, t: 25 },
      ],
    };
    expect(getStructuralSignature(node1)).toBe(getStructuralSignature(node2));
  });
});

describe("isPriceValue", () => {
  it("should detect price values", () => {
    expect(isPriceValue("$23")).toBe(true);
    expect(isPriceValue("$50.00")).toBe(true);
    expect(isPriceValue("99")).toBe(true);
  });

  it("should detect price suffixes", () => {
    expect(isPriceValue("/ month")).toBe(true);
    expect(isPriceValue("/year")).toBe(true);
    expect(isPriceValue("/ seat")).toBe(true);
  });

  it("should not match non-prices", () => {
    expect(isPriceValue("Feature 1")).toBe(false);
    expect(isPriceValue("title")).toBe(false);
  });
});

describe("isListIndex", () => {
  it("should detect numbered indices", () => {
    expect(isListIndex("1")).toBe(true);
    expect(isListIndex("23")).toBe(true);
    expect(isListIndex("0")).toBe(true);
  });

  it("should not match mixed content", () => {
    expect(isListIndex("1a")).toBe(false);
    expect(isListIndex("Feature 1")).toBe(false);
  });
});

// ============================================================================
// Verbose expansion tests (no collapsing)
// ============================================================================

describe("Verbose expansion output", () => {
  it("should expand homogeneous children instead of collapsing", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "stars",
      s: 100,
      t: 6000,
      c: Array.from({ length: 3 }, (_, i) => ({
        i: `0:${i + 2}`,
        n: "container",
        s: 100,
        t: 100,
      })),
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("stars(v:6) #0:1:");
    expect(result).toContain("container #0:2");
    expect(result).toContain("container #0:3");
    expect(result).toContain("container #0:4");
  });

  it("should keep generic wrappers and single children", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "card",
      s: 100,
      t: 500,
      c: [
        {
          i: "0:2",
          n: "container",
          s: 50,
          t: 200,
          c: [{ i: "0:3", n: "title", s: 50, t: 50 }],
        },
      ],
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("card(v:3) #0:1:");
    expect(result).toContain("container(v:2) #0:2:");
    expect(result).toContain("title #0:3");
  });

  it("should expand instance internals", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "page",
      s: 100,
      t: 10000,
      c: [
        {
          i: "I0:1;123:456",
          n: "component-instance",
          s: 500,
          t: 5000,
          c: [
            {
              i: "I0:1;123:456;789:012",
              n: "deep-nested",
              s: 200,
              t: 2000,
              c: [{ i: "I0:1;123:456;789:012;111:222", n: "deeper", s: 100, t: 100 }],
            },
          ],
        },
      ],
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("component-instance(v:6) #I0:1;123:456:");
    expect(result).toContain("deep-nested(v:5) #I0:1;123:456;789:012:");
    expect(result).toContain("deeper #I0:1;123:456;789:012;111:222");
  });

  it("should expand decorative children even at high volume", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "pattern-bg",
      s: 100,
      t: 15000, // v:7
      c: [
        { i: "0:2", n: "path", s: 100, t: 200 },
        { i: "0:3", n: "path", s: 100, t: 200 },
      ],
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("pattern-bg(v:7) #0:1:");
    expect(result).toContain("path #0:2");
    expect(result).toContain("path #0:3");
  });

  it("should keep icon names verbatim", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "vuesax-linear-check-circle",
      s: 100,
      t: 500,
      c: [{ i: "0:2", n: "vector", s: 50, t: 50 }],
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("vuesax-linear-check-circle(v:3) #0:1:");
    // "vector" matches auto-generated pattern, so it's normalized to "container"
    expect(result).toContain("container #0:2");
  });
});

// ============================================================================
// Integration Tests
// ============================================================================

describe("skeletonToDSL", () => {
  it("should convert simple leaf node", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "title",
      s: 50,
      t: 50,
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toBe("title #0:1");
  });

  it("should convert price node", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "$23",
      s: 50,
      t: 50,
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toBe('price #0:1: "$23"');
  });

  it("should convert node with children", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "card",
      s: 100,
      t: 500,
      c: [
        { i: "0:2", n: "title", s: 50, t: 50 },
        { i: "0:3", n: "subtitle", s: 50, t: 50 },
      ],
    };
    const result = skeletonToDSL(skeleton);
    expect(result).toContain("card(v:3) #0:1:");
    expect(result).toContain("title #0:2");
    expect(result).toContain("subtitle #0:3");
  });

  it("should add source file reference", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:1",
      n: "page",
      s: 100,
      t: 100,
    };
    const result = skeletonToDSL(skeleton, { sourceFile: "design.figma.json" });
    expect(result).toContain("@source: design.figma.json");
  });
});

describe("expandedSkeletonToDSL", () => {
  it("should convert expanded skeleton format", () => {
    const skeleton: NodeSkeleton = {
      id: "0:1",
      name: "header",
      selfTokenCount: 50,
      totalTokenCount: 150,
      children: [
        { id: "0:2", name: "title", selfTokenCount: 50, totalTokenCount: 50 },
        { id: "0:3", name: "subtitle", selfTokenCount: 50, totalTokenCount: 50 },
      ],
    };
    const result = expandedSkeletonToDSL(skeleton);
    expect(result).toContain("header(v:2) #0:1:");
    expect(result).toContain("title #0:2");
    expect(result).toContain("subtitle #0:3");
  });
});

describe("skeletonsToDSL", () => {
  it("should convert multiple skeletons with blank lines", () => {
    const skeletons: CompactNodeSkeleton[] = [
      { i: "0:1", n: "card-1", s: 50, t: 50 },
      { i: "0:2", n: "card-2", s: 50, t: 50 },
    ];
    const result = skeletonsToDSL(skeletons);
    expect(result).toBe("card-1 #0:1\n\ncard-2 #0:2");
  });
});

describe("Complex nested structure with collapse rules", () => {
  it("should produce compact output for real-world component", () => {
    const skeleton: CompactNodeSkeleton = {
      i: "0:100",
      n: "product-card",
      s: 71,
      t: 10500,
      c: [
        {
          i: "0:101",
          n: "Frame 2087327528", // Auto-generated, single child → skip
          s: 33,
          t: 3024,
          c: [
            {
              i: "0:102",
              n: "header",
              s: 20,
              t: 200,
              c: [
                { i: "0:103", n: "ic-star", s: 100, t: 100 }, // Icon
                { i: "0:104", n: "title", s: 50, t: 50 },
              ],
            },
          ],
        },
        {
          i: "0:105",
          n: "features",
          s: 35,
          t: 600,
          c: [
            { i: "0:106", n: "item", s: 100, t: 100 },
            { i: "0:107", n: "item", s: 100, t: 100 },
            { i: "0:108", n: "item", s: 100, t: 100 },
            { i: "0:109", n: "item", s: 100, t: 100 },
          ],
        },
        {
          i: "0:110",
          n: "Button",
          s: 30,
          t: 100,
          c: [{ i: "0:111", n: "label", s: 50, t: 50 }],
        },
      ],
    };

    const result = skeletonToDSL(skeleton);

    expect(result).toContain("product-card(v:7) #0:100:");
    // "Frame 2087327528" is auto-generated, so it's normalized to "container"
    expect(result).toContain("container(v:5) #0:101:");
    expect(result).toContain("header(v:2) #0:102:");
    expect(result).toContain("ic-star #0:103");
    expect(result).toContain("title #0:104");
    expect(result).toContain("features(v:3) #0:105:");
    expect(result).toContain("item #0:106");
    expect(result).toContain("item #0:107");
    expect(result).toContain("item #0:108");
    expect(result).toContain("item #0:109");
    expect(result).toContain("button(v:2) #0:110:");
    expect(result).toContain("label #0:111");
  });
});
