import { defineConfig } from 'tsup';
import { readFileSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

const sharedNoExternal = [
  '@frontman-ai/frontman-core',
  '@frontman-ai/frontman-protocol',
  '@frontman/bindings',
  '@rescript/runtime',
  'sury',
  'dom-element-to-component-source',
];

const sharedExternal = [
  'astro',
  'astro/toolbar',
  'astro/config',
  'lighthouse',
  'chrome-launcher',
  'source-map',
  'node:module',
  'fs',
  'path',
  'os',
  'child_process',
  'crypto',
  'util',
  'stream',
  'stream/web',
  'events',
  'buffer',
  'url',
  'http',
  'https',
  'net',
  'tls',
  'zlib',
  'readline',
  'tty',
  'assert',
  'process',
];

export default defineConfig([
  {
    entry: { 'index': './index.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: true,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: sharedNoExternal,
    external: sharedExternal,
    platform: 'node',
    target: 'node22',
    treeshake: true,
  },
  {
    entry: { 'integration': './src/FrontmanAstro__Integration.res.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: false,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: sharedNoExternal,
    external: sharedExternal,
    platform: 'node',
    target: 'node22',
    treeshake: true,
  },
  {
    entry: { 'toolbar': './src/FrontmanAstro__ToolbarApp.res.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: false,
    define: { '__PACKAGE_VERSION__': JSON.stringify(pkg.version) },
    noExternal: sharedNoExternal,
    external: sharedExternal,
    platform: 'browser',
    target: 'es2020',
    treeshake: true,
  },
  {
    entry: { 'mcp-json-schema-worker': '../frontman-core/src/mcp-json-schema-worker.mjs' },
    format: ['esm'],
    outDir: 'dist',
    outExtension: () => ({ js: '.mjs' }),
    clean: false,
    noExternal: ['ajv'],
    platform: 'node',
    target: 'node22',
    treeshake: true,
  },
]);
