
global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - match:
        severity: critical
      receiver: discord
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

receivers:
  - name: discord
    webhook_configs:
      - url: http://127.0.0.1:9095
        send_resolved: true

inhibit_rules:
  - source_match:
      alertname: DiskSpaceCritical
    target_match:
      alertname: DiskSpaceWarning
    equal: [instance, mountpoint]
