import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: { 'index': './src/FrontmanVite.res.mjs' },
    format: ['esm'],
    outDir: 'dist',
    clean: true,
    dts: true,
    // Bundle internal workspace dependencies
    noExternal: [
      '@frontman/frontman-core',
      '@frontman/frontman-protocol',
      '@frontman/bindings',
      '@rescript/runtime',
      'sury',
      'dom-element-to-component-source',
    ],
    // Keep these as external (user must install or are runtime-provided)
    external: [
      'vite',
      // Node.js built-ins
      'fs',
      'path',
      'os',
      'child_process',
      'crypto',
      'util',
      'stream',
      'events',
      'buffer',
      'url',
      'http',
      'https',
      'net',
      'tls',
      'zlib',
      'readline',
      'tty',
      'assert',
      'process',
      'node:fs',
      'node:path',
      'node:os',
      'node:child_process',
      'node:crypto',
      'node:util',
      'node:stream',
      'node:events',
      'node:buffer',
      'node:url',
      'node:http',
      'node:https',
      'node:module',
    ],
    platform: 'node',
    target: 'node18',
    treeshake: true,
  },
]);
