defmodule FrontmanServer.Providers.ChatGPTOAuth do
  @moduledoc """
  Handles OAuth authentication for ChatGPT Pro/Plus subscriptions.

  Implements the Device Auth flow against OpenAI's auth server:
  1. Request a device code (user_code) from OpenAI
  2. User opens https://auth.openai.com/codex/device and enters the code
  3. Server polls OpenAI until user authorizes → receives authorization_code + PKCE
  4. Exchange authorization_code for access/refresh/id tokens
  5. Extract chatgpt_account_id from JWT claims
  6. Refresh tokens when expired

  Uses the same public OAuth client_id as Codex CLI.
  The device auth flow is required because this client_id only allows
  http://localhost:* redirect URIs (it's a native/public client).
  """

  require Logger

  alias FrontmanServer.Providers.OAuthToken

  @client_id "app_EMoamEEZ73f0CkXaXp7hrann"
  @issuer "https://auth.openai.com"
  @token_url "#{@issuer}/oauth/token"
  @device_code_url "#{@issuer}/api/accounts/deviceauth/usercode"
  @device_token_url "#{@issuer}/api/accounts/deviceauth/token"
  @verification_url "#{@issuer}/codex/device"
  @device_redirect_uri "#{@issuer}/deviceauth/callback"

  @doc """
  Returns the OAuth client_id.
  """
  def client_id, do: @client_id

  @doc """
  Returns the verification URL where the user enters their device code.
  """
  def verification_url, do: @verification_url

  @doc """
  Step 1: Request a device code from OpenAI.

  Returns `{:ok, %{device_auth_id: ..., user_code: ..., interval: ...}}`
  or `{:error, reason}`.

  The `interval` is the polling interval in seconds.
  """
  @spec request_device_code() ::
          {:ok, %{device_auth_id: String.t(), user_code: String.t(), interval: integer()}}
          | {:error, term()}
  def request_device_code do
    body = Jason.encode!(%{"client_id" => @client_id})

    headers = [
      {"content-type", "application/json"},
      {"accept", "application/json"}
    ]

    case Req.post(@device_code_url, body: body, headers: headers) do
      {:ok, %Req.Response{status: status, body: response_body}} when status in 200..299 ->
        device_auth_id = response_body["device_auth_id"]
        user_code = response_body["user_code"] || response_body["usercode"]
        interval = parse_interval(response_body["interval"])

        if device_auth_id && user_code do
          {:ok, %{device_auth_id: device_auth_id, user_code: user_code, interval: interval}}
        else
          Logger.error("ChatGPT device code response missing fields: #{inspect(response_body)}")
          {:error, :invalid_response}
        end

      {:ok, %Req.Response{status: 404}} ->
        {:error, :device_auth_not_enabled}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error(
          "ChatGPT device code request failed: status=#{status}, body=#{inspect(body)}"
        )

        {:error, {:device_code_failed, status, body}}

      {:error, reason} ->
        Logger.error("ChatGPT device code request error: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Step 2: Poll OpenAI to check if the user has authorized.

  Returns:
  - `{:ok, %{authorization_code: ..., code_verifier: ...}}` when user has authorized
  - `{:pending}` when user hasn't authorized yet
  - `{:error, reason}` on failure

  The `code_verifier` is server-generated by OpenAI (not standard PKCE).
  """
  @spec poll_device_token(String.t(), String.t()) ::
          {:ok, %{authorization_code: String.t(), code_verifier: String.t()}}
          | {:pending}
          | {:error, term()}
  def poll_device_token(device_auth_id, user_code) do
    body = Jason.encode!(%{"device_auth_id" => device_auth_id, "user_code" => user_code})

    headers = [
      {"content-type", "application/json"},
      {"accept", "application/json"}
    ]

    case Req.post(@device_token_url, body: body, headers: headers) do
      {:ok, %Req.Response{status: 200, body: response_body}} ->
        authorization_code = response_body["authorization_code"]
        code_verifier = response_body["code_verifier"]

        if authorization_code && code_verifier do
          {:ok, %{authorization_code: authorization_code, code_verifier: code_verifier}}
        else
          Logger.error("ChatGPT device token response missing fields: #{inspect(response_body)}")

          {:error, :invalid_response}
        end

      {:ok, %Req.Response{status: status}} when status in [403, 404] ->
        # User hasn't authorized yet
        {:pending}

      {:ok, %Req.Response{status: 401, body: body}} ->
        Logger.error("ChatGPT device auth declined: #{inspect(body)}")
        {:error, :authorization_declined}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error("ChatGPT device token poll failed: status=#{status}, body=#{inspect(body)}")

        {:error, {:poll_failed, status, body}}

      {:error, reason} ->
        Logger.error("ChatGPT device token poll request error: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Step 3: Exchange the authorization code (from device flow) for tokens.

  Uses the server-generated `code_verifier` from the poll response and
  OpenAI's device auth callback as the redirect_uri.

  Returns `{:ok, %{access_token: ..., refresh_token: ..., id_token: ..., expires_in: ...}}`
  or `{:error, reason}`.
  """
  @spec exchange_device_code(String.t(), String.t()) ::
          {:ok,
           %{
             access_token: String.t(),
             refresh_token: String.t(),
             id_token: String.t(),
             expires_in: integer() | nil
           }}
          | {:error, term()}
  def exchange_device_code(authorization_code, code_verifier) do
    body =
      URI.encode_query(%{
        "grant_type" => "authorization_code",
        "code" => authorization_code,
        "redirect_uri" => @device_redirect_uri,
        "client_id" => @client_id,
        "code_verifier" => code_verifier
      })

    headers = [
      {"content-type", "application/x-www-form-urlencoded"},
      {"accept", "application/json"}
    ]

    case Req.post(@token_url, body: body, headers: headers) do
      {:ok,
       %Req.Response{
         status: 200,
         body:
           %{
             "access_token" => access_token,
             "id_token" => id_token,
             "refresh_token" => refresh_token
           } = response_body
       }} ->
        {:ok,
         %{
           access_token: access_token,
           refresh_token: refresh_token,
           id_token: id_token,
           expires_in: response_body["expires_in"]
         }}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error(
          "ChatGPT device code exchange failed: status=#{status}, body=#{inspect(body)}"
        )

        {:error, {:token_exchange_failed, status, body}}

      {:error, reason} ->
        Logger.error("ChatGPT device code exchange request failed: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Refreshes an access token using the refresh token.

  Returns `{:ok, %{access_token: ..., refresh_token: ..., id_token: ..., expires_in: ...}}`
  or `{:error, reason}`.
  """
  @spec refresh_token(String.t()) ::
          {:ok,
           %{
             access_token: String.t(),
             refresh_token: String.t() | nil,
             id_token: String.t() | nil,
             expires_in: integer() | nil
           }}
          | {:error, term()}
  def refresh_token(refresh_token) do
    body =
      URI.encode_query(%{
        "grant_type" => "refresh_token",
        "refresh_token" => refresh_token,
        "client_id" => @client_id
      })

    headers = [
      {"content-type", "application/x-www-form-urlencoded"},
      {"accept", "application/json"}
    ]

    case Req.post(@token_url, body: body, headers: headers) do
      {:ok, %Req.Response{status: 200, body: response_body}} ->
        {:ok,
         %{
           access_token: response_body["access_token"],
           refresh_token: response_body["refresh_token"],
           id_token: response_body["id_token"],
           expires_in: response_body["expires_in"]
         }}

      {:ok, %Req.Response{status: status, body: body}} ->
        Logger.error(
          "ChatGPT OAuth token refresh failed: status=#{status}, body=#{inspect(body)}"
        )

        {:error, {:token_refresh_failed, status, body}}

      {:error, reason} ->
        Logger.error("ChatGPT OAuth token refresh request failed: #{inspect(reason)}")
        {:error, {:request_failed, reason}}
    end
  end

  @doc """
  Calculates the expiration DateTime from expires_in seconds.
  """
  @spec calculate_expires_at(integer()) :: DateTime.t()
  defdelegate calculate_expires_at(expires_in), to: OAuthToken

  @doc """
  Extracts the chatgpt_account_id from a JWT token (id_token or access_token).

  Parses the JWT payload and looks for the account ID in these locations:
  1. `https://api.openai.com/auth` -> `chatgpt_account_id`
  2. Top-level `chatgpt_account_id`
  3. First organization ID from `organizations` array

  Returns `{:ok, account_id}` or `{:error, :not_found}`.
  """
  @spec extract_account_id(String.t()) :: {:ok, String.t()} | {:error, :not_found}
  def extract_account_id(jwt) when is_binary(jwt) do
    case decode_jwt_payload(jwt) do
      {:ok, claims} ->
        account_id =
          get_in(claims, ["https://api.openai.com/auth", "chatgpt_account_id"]) ||
            claims["chatgpt_account_id"] ||
            get_first_org_id(claims)

        case account_id do
          id when is_binary(id) and id != "" -> {:ok, id}
          _ -> {:error, :not_found}
        end

      {:error, _} ->
        {:error, :not_found}
    end
  end

  def extract_account_id(_), do: {:error, :not_found}

  @doc """
  Extracts the account ID from token response, trying id_token first, then access_token.
  """
  @spec extract_account_id_from_tokens(%{
          required(:id_token) => String.t(),
          required(:access_token) => String.t(),
          optional(atom()) => any()
        }) :: String.t() | nil
  def extract_account_id_from_tokens(%{id_token: id_token, access_token: access_token}) do
    case extract_account_id(id_token) do
      {:ok, id} ->
        id

      {:error, _} ->
        case extract_account_id(access_token) do
          {:ok, id} -> id
          {:error, _} -> nil
        end
    end
  end

  # Private helpers

  defp parse_interval(nil), do: 5
  defp parse_interval(val) when is_integer(val), do: val

  defp parse_interval(val) when is_binary(val) do
    case Integer.parse(val) do
      {n, _} -> n
      :error -> 5
    end
  end

  defp parse_interval(_), do: 5

  defp decode_jwt_payload(jwt) do
    case String.split(jwt, ".") do
      [_header, payload, _signature] ->
        # Add padding if necessary for base64url decoding
        padded = pad_base64url(payload)

        case Base.url_decode64(padded, padding: false) do
          {:ok, json} -> Jason.decode(json)
          :error -> {:error, :invalid_base64}
        end

      _ ->
        {:error, :invalid_jwt}
    end
  end

  defp pad_base64url(str) do
    case rem(byte_size(str), 4) do
      2 -> str <> "=="
      3 -> str <> "="
      _ -> str
    end
  end

  defp get_first_org_id(%{"organizations" => [%{"id" => id} | _]}) when is_binary(id), do: id
  defp get_first_org_id(_), do: nil
end
